# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: copier.proto for package 'copier'

require 'grpc'
require_relative 'copier_pb'

module Copier
  module CopierService
    # Trade copier operations over gRPC.
    #
    # This exists for one reason: the REST equivalents take the master's and slave's MT account
    # PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    # between, and to the browser's history — so every copier ever started has put two sets of live
    # trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    # where nothing on the path records them.
    #
    # The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    # the same operations, not a replacement, and it delegates to exactly the same implementation so
    # the two cannot drift.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'copier.CopierService'

      # Start a copier. The only call that carries credentials.
      rpc :Start, ::Copier::StartRequest, ::Copier::StartReply
      # Every copier belonging to a user. Never returns stored passwords — see CopierSummary.
      rpc :List, ::Copier::ListRequest, ::Copier::ListReply
      # Pause or resume.
      rpc :Pause, ::Copier::PauseRequest, ::Copier::SimpleReply
      # Remove a copier.
      rpc :Remove, ::Copier::RemoveRequest, ::Copier::SimpleReply
    end

    Stub = Service.rpc_stub_class
  end
end
