# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: copier.proto for package 'copier'

require 'grpc'
require_relative 'copier_pb'

module Copier
  module CopierService
    # Trade copier operations over gRPC.
    #
    # Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
    # preventing plain-text credential leakage in HTTP query parameters, server access logs,
    # or proxy routing histories.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'copier.CopierService'

      # Start a trade copier between master and slave accounts.
      rpc :Start, ::Copier::StartRequest, ::Copier::StartReply
      # List all active and paused copiers belonging to a user.
      rpc :List, ::Copier::ListRequest, ::Copier::ListReply
      # Pause or resume an existing copier without deleting configuration.
      rpc :Pause, ::Copier::PauseRequest, ::Copier::SimpleReply
      # Remove a copier and unregister trade hooks.
      rpc :Remove, ::Copier::RemoveRequest, ::Copier::SimpleReply
    end

    Stub = Service.rpc_stub_class
  end
  module DemoAccount
    # Demo account creation service definition
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'copier.DemoAccount'

      # Provision a new MetaTrader demo account on the fly.
      rpc :OpenDemoAccount, ::Copier::GuiDemoOpenAccountRequest, ::Copier::GuiDemoOpenAccountReply
    end

    Stub = Service.rpc_stub_class
  end
end
